apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: price-service
  name: price-service-deployment
spec:
  template:
    spec:
      containers:
      - name: price-service
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 1000m
            memory: 512Mi
            

